name: 🏸 Check Badminton Slots

on:
  workflow_dispatch:
    inputs:
      booking_date:
        description: "Date to check (YYYY-MM-DD)"
        required: true
      venue_id:
        description: "Venue ID"
        required: false
        default: "1"

jobs:
  check-slots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Slot Checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BOOKING_DATE: ${{ github.event.inputs.booking_date }}
          VENUE_ID: ${{ github.event.inputs.venue_id }}
        run: node slotChecker.js
